### ISSUE TITLE
Campo não existente

### ISSUE THREAD

**Issue by evandrogrm** [Samuel-Oliveira/Java-Efd-Icms#1]
https://github.com/Samuel-Oliveira/Java-Efd-Icms/blob/65f90e657fd5dddbf696dc3bc5fcf701216f915d/src/main/java/br/com/swconsultoria/efd/icms/registros/blocoK/RegistroK250.java#L18

Bom dia, este último campo não existe no registro K250.
Att.

**Comment by Samuel-Oliveira** [comment]
OLá, Obrigado por avisar, vou dar uma olhada e te retorno!

**Comment by Samuel-Oliveira** [comment]
Corrigido!
