### ISSUE TITLE
Jar nao disponivel para download 

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java-Efd-Icms#2]
Ao tentar baixar o jar direto aqui no git da erro 404

**Comment by resplandes** [comment]
Lembrando que baixei do mesmo jeito, clonando o diretorio

**Comment by jrmazalli** [comment]
https://github.com/Samuel-Oliveira/Java-Efd-Icms/raw/master/java-efd-icms-3.08.2.jar

só a versão que do link que esta direcionando para o antigo, link correto acima.
