### ISSUE TITLE
REG K010 - Leiaute 2023

### ISSUE THREAD

**Issue by RodrigoFBecher** [Samuel-Oliveira/Java-Efd-Icms#5]
Olá, com o leiaute 2023 surgiu o REG K010, registro do bloco K, obrigatório se o campo 02 (IND_MOV) do registro K001 estiver informado com "0 - Bloco Com dados informados".

Alguma sugestão de guideline para implementação desse novo registro na biblioteca? Estou disposto a abrir um pull-request com as alterações necessárias.

Obrigado.

**Comment by Samuel-Oliveira** [comment]
Blz Rodrigo? 
Vou implementar o Laiout 2023 agora em dezembro!
Dai vou adicionar todos os campos novos!

**Comment by Samuel-Oliveira** [comment]
Feito!
