### ISSUE TITLE
Sugestão de correções

### ISSUE THREAD

**Issue by marciorl** [Samuel-Oliveira/Java-Efd-Icms#8]
Arquivo br.com.swconsultoria.efd.icms.bo.blocoC.GerarRegistroC855.java

Modificar linha 15 de:

`sb.append("|").append(Util.preencheRegistro(registroC855.getCod_obs()));`

Para:

`sb.append("|").append(Util.preencheRegistro(registroC855.getTxt_compl()));`

Arquivo br.com.swconsultoria.efd.icms.registros.blocoC.RegistroC895.java

Modificar linha 14 de:

`private final String reg = "C890";`

Para:

`private final String reg = "C895";`

Arquivo br.com.swconsultoria.efd.icms.bo.blocoC.GerarRegistroC895.java

Modificar linha 15 de:

`sb.append("|").append(Util.preencheRegistro(registroC895.getCod_obs()));`

Para:

`sb.append("|").append(Util.preencheRegistro(registroC895.getTxt_compl()));`

**Comment by samuel-oliveira-tr** [comment]
Feito, Agradeco. Precisa de nova versao?
