### ISSUE TITLE
Erro na contagem do registro 1910/1920

### ISSUE THREAD

**Issue by demerval** [Samuel-Oliveira/Java-Efd-Icms#9]
Na classe:
```package br.com.swconsultoria.efd.icms.bo.bloco1.GerarBloco1```

A linha 236 está incrementando o registro 1910.
```efdIcms.getContadoresBloco1().incrementar(Bloco1Enum.Registro1910);```

Fiz a alteração para 1920.
```efdIcms.getContadoresBloco1().incrementar(Bloco1Enum.Registro1920);```

Resolveu o erro na contagem dos registros.

**Comment by Samuel-Oliveira** [comment]
Obrigado por notificar.
Corrigido no codigo!
Deseja q gere versao ou ja esta usando uma ?
